### ISSUE TITLE
New release + question on difference to libusb/hidapi

### ISSUE THREAD

**Issue by ghost** [supercollider/hidapi#12]
I'm in the process of updating SuperCollider for pkgsrc.

The updated version requires this library. The latest tag / released version is from 2011. Can you please tag a new release?

(Follow-up question: Do you intend to / have already merged back to https://github.com/libusb/hidapi which is the new upstream for hidapi? (ie: is this hidapi a requirement, or can the libusb one be used, and if not, what is the difference?))

Thanks.

**Comment by mossheim** [comment]
Hi @ng-0, sorry for the late reply.

> I'm in the process of updating SuperCollider for pkgsrc.

What is pkgsrc?

> The latest tag / released version is from 2011. Can you please tag a new release?

Sure, I will try to do that soon.

> Do you intend to / have already merged back to https://github.com/libusb/hidapi which is the new upstream for hidapi?

No.

**Comment by mossheim** [comment]
I have added a new tag: https://github.com/supercollider/hidapi/releases/tag/hidapi-sc-0.8.0

I added the infix `sc` to indicate that this is a release from the SC fork of hidapi, and also to help prevent any potential tagging conflicts in the future.

**Comment by ghost** [comment]
Thanks!
